apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  labels:
    version: 0.0.6
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - image: corelab/ks-guestbook-demo:0.2
          name: guestbook-ui
          ports:
            - containerPort: 80
$:
  metadata:
    labels:
      version: 0.0.6
  spec:
    template:
      spec:
        containers:
          - image: corelab/ks-guestbook-demo:0.1
/metadata/labels/version: 0.0.6
/spec/template/spec/containers/0/image: corelab/ks-guestbook-demo:0.1
